"""Business-model-aware valuation dispatch. Inputs are analyst assumptions, not estimates generated by an LLM."""
from __future__ import annotations
import copy
from datetime import timedelta
from .contracts import require, number, text, iso_date
from .models import valuations as legacy_valuations, dcf
from .routing import resolve, entity_sector, source_sectors


def positive(value, label):
    x=number(value,label)
    require(x>0, f'{label}: positive value required')
    return x


def value_models(brief: dict) -> list[dict]:
    models=brief.get('valuation_models',[])
    require(isinstance(models,list), 'valuation_models must be a list')
    bundle=resolve(brief)
    entities={e['id']:e for e in brief['universe']}
    known_sources={s['id'] for s in brief.get('sources',[])}
    seen=set(); results=[]
    for model in models:
        require(isinstance(model,dict),'Valuation model must be an object')
        eid=model.get('entity')
        require(isinstance(eid,str) and eid in entities and eid not in seen, 'Unknown or duplicate valuation entity')
        seen.add(eid)
        entity=entities[eid]; sid=entity_sector(entity,bundle)
        methods=bundle['sectors'][sid]['subsectors'][entity['subsector']]['valuation_methods']
        ids=model.get('source_ids')
        require(isinstance(ids,list) and bool(ids) and all(isinstance(x,str) for x in ids) and set(ids)<=known_sources,
                'Valuation requires valid source IDs')
        linked=[s for s in brief.get('sources',[]) if s['id'] in ids]
        require(any(sid in source_sectors(s,brief,bundle) for s in linked),
                f'{eid}: model input sources do not include evidence scoped to its sector')
        method=model.get('method')
        require(method in methods, f'{eid}: {method} is not appropriate for {sid}/{entity["subsector"]}; permitted: {methods}')
        if method in {'multiple','dcf','rnpv'}:
            subset=copy.deepcopy(brief); subset['valuation_models']=[model]
            item=legacy_valuations(subset)[0]
            item['sector']=sid
            results.append(item)
            continue
        text(model.get('currency'),'currency')
        require(model.get('units')=='millions','units must be millions; share metrics are currency per diluted share')
        require(model.get('basis')=='as_of_present_value','basis must be as_of_present_value')
        text(model.get('assumptions_note'),'assumptions_note')
        ids=model.get('source_ids')
        require(isinstance(ids,list) and bool(ids) and all(isinstance(x,str) for x in ids) and set(ids)<=known_sources,
                'Valuation requires valid source IDs')
        as_of=iso_date(brief['as_of'],'as_of'); price_date=iso_date(model.get('price_as_of'),'price_as_of')
        require(as_of-timedelta(days=7)<=price_date<=as_of,'Price is after cut-off or older than 7 days')
        price=positive(model.get('price'),'price'); shares=positive(model.get('diluted_shares'),'diluted_shares')
        cases=model.get('scenarios')
        require(isinstance(cases,list) and len(cases)==3 and all(isinstance(c,dict) for c in cases), 'Exactly three scenarios required')
        require({c.get('name') for c in cases}=={'bear','base','bull'},'Need unique bear/base/bull')
        values=[]; total=0.0
        for case in cases:
            p=number(case.get('probability'),'probability'); require(0<=p<=1,'Probability outside [0,1]'); total+=p
            ev=None
            if method in {'pe','ptbv','ffo','affo'}:
                metric={'pe':'eps','ptbv':'tangible_book_per_share','ffo':'ffo_per_share','affo':'affo_per_share'}[method]
                per_share=positive(case.get(metric),metric)*positive(case.get('multiple'),'multiple')
                # These are equity metrics: never add cash or subtract bank deposits/debt a second time.
                equity=per_share*shares
            elif method=='ddm':
                dividends=case.get('dividends_per_share')
                require(isinstance(dividends,list) and dividends and all(number(x,'dividend')>=0 for x in dividends),
                        'DDM requires nonnegative annual per-share dividends')
                per_share=dcf(dividends,case.get('cost_of_equity'),case.get('terminal_growth'))
                equity=per_share*shares
            elif method=='nav':
                assets=case.get('properties')
                require(isinstance(assets,list) and assets,'NAV requires income-property records')
                ev=0.0; names=set()
                for asset in assets:
                    require(isinstance(asset,dict),'Property record must be an object')
                    name=text(asset.get('name'),'property.name'); require(name not in names,'Duplicate NAV property'); names.add(name)
                    noi=number(asset.get('noi'),'noi'); cap=positive(asset.get('cap_rate'),'cap_rate')
                    require(noi>=0 and cap<1,'NAV requires nonnegative cash NOI and cap rate below 1')
                    ev+=noi/cap
                for key in ('other_assets','cash','debt','other_claims'):
                    require(number(case.get(key),key)>=0,f'{key} must be nonnegative')
                ev+=case['other_assets']
                equity=max(0.0,ev+case['cash']-case['debt']-case['other_claims'])
                per_share=equity/shares
            else:
                raise ValueError(f'Unimplemented valuation method: {method}')
            values.append({'name':case['name'],'probability':p,'enterprise_value':ev,
                           'equity_value':number(equity,'equity value'),'value_per_share':number(per_share,'value/share'),
                           'upside':number(per_share/price-1,'upside')})
        require(abs(total-1)<=1e-8,'Scenario probabilities must sum to 1')
        order={c['name']:c['value_per_share'] for c in values}
        require(order['bear']<=order['base']<=order['bull'],'Scenario values are not bear <= base <= bull')
        expected=sum(c['probability']*c['value_per_share'] for c in values)
        results.append({'entity':eid,'sector':sid,'method':method,'currency':model['currency'], 'units':model['units'],
                        'price_as_of':model['price_as_of'],'scenarios':values,'expected_value_per_share':expected,
                        'expected_upside':expected/price-1,'reverse_valuation':None,'source_ids':ids,
                        'assumptions_note':model['assumptions_note'],
                        'limitations':'Analyst-input scenarios, not independent forecasts. Equity multiples and DDM have no second net-debt adjustment. NAV uses supplied ownership-adjusted cash NOI, assets and claims; no automatic property appraisal, debt waterfall or tax model. AFFO definitions require issuer reconciliation.'})
    for item in results:
        number(item['expected_value_per_share'],'expected value/share')
        number(item['expected_upside'],'expected upside')
    return results
